var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/sessions/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0trgn_y._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0qx~~i8.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~qbcbi._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ngiev5._.js")
R.c("server/chunks/ssr/app_layout_04hilog.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/app_dashboard_layout_0_g6ure.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_sessions_page_actions_05l9mw7.js")
R.m(66472)
module.exports=R.m(66472).exports
